const UPDATE_MANAGER_MODULE_SETTING = 'UPDATE_MANAGER_MODULE_SETTING';

const UPDATE_TEACHER_MODULE_SETTING = 'UPDATE_TEACHER_MODULE_SETTING';

const UPDATE_STUDENT_MODULE_SETTING = 'UPDATE_STUDENT_MODULE_SETTING';

const TIME_BARNER_SHOW = 'TIME_BARNER_SHOW';

const TIME_BARNER_HIDE = 'TIME_BARNER_HIDE';

const MODULE_SETTINGS_UPDATE = 'MODULE_SETTINGS_UPDATE';

export default {

    UPDATE_MANAGER_MODULE_SETTING,

    UPDATE_TEACHER_MODULE_SETTING,

    UPDATE_STUDENT_MODULE_SETTING,

    TIME_BARNER_SHOW,

    TIME_BARNER_HIDE,

    MODULE_SETTINGS_UPDATE

}