import TPActions from './TeacherPageActions';


const TEACHER_HEADER_MENU_TOGGLE = 'TEACHER_HEADER_MENU_TOGGLE';

const TEACHER_HEADER_MENU_SHOW = 'TEACHER_HEADER_MENU_SHOW';

const TEACHER_HEADER_MENU_HIDE = 'TEACHER_HEADER_MENU_HIDE';

const TEACHER_HEADER_SUBJECTS_UPDATE = 'TEACHER_HEADER_SUBJECTS_UPDATE';

const TEACHER_HEADER_SUBJECTS_PICK_CHANGE = 'TEACHER_HEADER_SUBJECTS_PICK_CHANGE';

const TEACHER_SUBJECT_MENU_TOGGLE = 'TEACHER_SUBJECT_MENU_TOGGLE';

const TEACHER_SUBJECT_MENU_SHOW = 'TEACHER_SUBJECT_MENU_SHOW';

const TEACHER_SUBJECT_MENU_HIDE = 'TEACHER_SUBJECT_MENU_HIDE';

const TEACHER_CUSTOM_MODAL_OPEN = 'TEACHER_CUSTOM_MODAL_OPEN'

const TEACHER_CUSTOM_MODAL_CLOSE = 'TEACHER_CUSTOM_MODAL_CLOSE'


//点击头部的教师的学科

const SubjectClick = (info) => {

    return (dispatch,getState)=>{

        dispatch({type:TEACHER_HEADER_SUBJECTS_PICK_CHANGE,data:info});

        //let SubjectID = info.id;

        dispatch(TPActions.PageUpdate());

    }

};




export default {

    TEACHER_HEADER_MENU_TOGGLE,

    TEACHER_HEADER_MENU_SHOW,

    TEACHER_HEADER_MENU_HIDE,

    TEACHER_HEADER_SUBJECTS_UPDATE,

    TEACHER_HEADER_SUBJECTS_PICK_CHANGE,

    TEACHER_SUBJECT_MENU_TOGGLE,

    TEACHER_SUBJECT_MENU_SHOW,

    TEACHER_SUBJECT_MENU_HIDE,

    SubjectClick,

    TEACHER_CUSTOM_MODAL_CLOSE,

    TEACHER_CUSTOM_MODAL_OPEN

}