

const APP_LOADING_SHOW = 'APP_LOADING_SHOW';

const APP_LOADING_HIDE = 'APP_LOADING_HIDE';

const MODAL_LOADING_OPEN = 'MODAL_LOADING_OPEN';

const MODAL_LOADING_CLOSE = 'MODAL_LOADING_CLOSE';

const CUSTOM_LOADING_OPEN = 'CUSTOM_LOADING_OPEN';

const CUSTOM_LOADING_CLOSE = 'CUSTOM_LOADING_CLOSE';

const CUSTOM_OPACITY_LOADING_OPEN = 'CUSTOM_OPACITY_LOADING_OPEN';

const CUSTOM_OPACITY_LOADING_CLOSE = 'CUSTOM_OPACITY_LOADING_CLOSE';

export default {

    APP_LOADING_HIDE,

    APP_LOADING_SHOW,

    MODAL_LOADING_OPEN,

    MODAL_LOADING_CLOSE,

    CUSTOM_LOADING_CLOSE,

    CUSTOM_LOADING_OPEN,

    CUSTOM_OPACITY_LOADING_OPEN,

    CUSTOM_OPACITY_LOADING_CLOSE

}