import TPActions from './TeacherPageActions';


const STUDENT_HEADER_MENU_TOGGLE = 'STUDENT_HEADER_MENU_TOGGLE';

const STUDENT_HEADER_MENU_SHOW = 'STUDENT_HEADER_MENU_SHOW';

const STUDENT_HEADER_MENU_HIDE = 'STUDENT_HEADER_MENU_HIDE';

const STUDENT_HEADER_SUBJECTS_UPDATE = 'STUDENT_HEADER_SUBJECTS_UPDATE';

const STUDENT_HEADER_SUBJECTS_PICK_CHANGE = 'STUDENT_HEADER_SUBJECTS_PICK_CHANGE';

const STUDENT_SUBJECT_MENU_TOGGLE = 'STUDENT_SUBJECT_MENU_TOGGLE';

const STUDENT_SUBJECT_MENU_SHOW = 'STUDENT_SUBJECT_MENU_SHOW';

const STUDENT_SUBJECT_MENU_HIDE = 'STUDENT_SUBJECT_MENU_HIDE';

const STUDENT_CUSTOM_MODAL_OPEN = 'STUDENT_CUSTOM_MODAL_OPEN';

const STUDENT_CUSTOM_MODAL_CLOSE = 'STUDENT_CUSTOM_MODAL_CLOSE';


//点击头部的教师的学科

const SubjectClick = (info) => {

    return (dispatch,getState)=>{

        dispatch({type:STUDENT_HEADER_SUBJECTS_PICK_CHANGE,data:info});

        //let SubjectID = info.id;

        dispatch(TPActions.PageUpdate());

    }

};




export default {

    STUDENT_HEADER_MENU_TOGGLE,

    STUDENT_HEADER_MENU_SHOW,

    STUDENT_HEADER_MENU_HIDE,

    STUDENT_HEADER_SUBJECTS_UPDATE,

    STUDENT_HEADER_SUBJECTS_PICK_CHANGE,

    STUDENT_SUBJECT_MENU_TOGGLE,

    STUDENT_SUBJECT_MENU_SHOW,

    STUDENT_SUBJECT_MENU_HIDE,

    SubjectClick,

    STUDENT_CUSTOM_MODAL_CLOSE,

    STUDENT_CUSTOM_MODAL_OPEN

}