const HEADER_MENU_TOGGLE = 'HEADER_MENU_TOGGLE';

const HEADER_MENU_HIDE = 'HEADER_MENU_HIDE';

const HEADER_MENU_SHOW = 'HEADER_MENU_SHOW';

const HEADER_STATICS_UPDATE = 'HEADER_STATICS_UPDATE';

export default {

    HEADER_MENU_TOGGLE,

    HEADER_MENU_SHOW,

    HEADER_MENU_HIDE,

    HEADER_STATICS_UPDATE

}